// Replace with real regional packages later (JSON file per region)
export const SPECIES = [
    'Tailed Jay', 'Fivebar Swordtail', 'Common Jay', 'Spot Swordtail', 'Common Bluebottle', 'Common Rose', 
    'Crimson Rose', 'Sri Lankan Rose', 'Mime', 'Banded Peacock', 'Lime Butterfly', 'Red Helen', 'Blue Mormon', 
    'Common Mormon', 'Sri Lankan Birdwing', 'Common Albatross', 'Sri Lankan Lesser Albatross', 'Plain Puffin', 
    'Striped Albatross', 'Chocolate Albatross', 'Pioneer', 'Lemon Emigrant', 'Mottled Emigrant', 'Orange Migrant', 
    'Lesser Gull', 'Common Gull', 'Small Salmon Arab', 'Plain Orange Tip', 'Crimson Tip', 'Little Orange Tip', 
    'Large Salmon Arab', 'Jezebel', 'One-spot Grass Yellow', 'Three-spot Grass Yellow', 'Small Grass Yellow', 
    'Common Grass Yellow', 'Spotless Grass Yellow', 'Great Orange Tip', 'White Orange Tip', 'Yellow Orange Tip', 
    'Psyche', 'Dark Wanderer', 'Painted Saw-tooth', 'Tawny Coster', 'Indian Fritillary', 'Angled Castor', 
    'Common Castor', 'Joker', 'Ceylon Lace Wing', 'Nawab', 'Tawny Rajah', 'Black Rajah', 'Tamil Yeoman/ Yeoman', 
    'Rustic', 'Plain Tiger', 'Common Tiger', 'Southern Duffer', 'Autumn Leaf', 'Redspot Duke', 'Common Palmfly', 
    'Sri Lankan Palmfly', 'Common Indian Crow', 'Brown King Crow', 'Great Crow', 'Double-branded Black Crow', 
    'Baron', 'Gaudy Baron', 'Great Eggfly', 'Danaid Eggfly', 'Sri Lankan Tree Nymph', 'Blue Glassy Tiger', 
    'Peacock Pansy', 'Grey Pansy', 'Yellow Pansy', 'Chocolate Soldier', 'Lemon Pansy', 'Blue Pansy', 
    'Sri Lankan Blue Oakleaf', 'Blue Admiral', 'Sri Lankan Treebrown', 'Tamil Treebrown', 'Sri Lankan Forester', 
    'Common Tree Brown', 'Beak', 'Club Beak', 'Common Evening Brown', 'Dark Evening Brown', 'Commander', 
    'Dark-brand Bushbrown', 'Gladeye Bushbrown', 'Common Bushbrown', 'Sri Lankan Cingalese Bushbrown', 
    'Sri Lankan Tamil Bushbrown', 'Common Sailor', 'Chestnut-streaked Sailor', 'Medus Brown', 'Common Lascar', 
    'Glassy Tiger', 'Sri Lankan Tiger/Monarch', 'Clipper', 'Small Leopard', 'Leopard', 'Black Prince', 
    'Baronet', 'Blue Tiger', 'Dark Blue Tiger', 'Painted Lady', 'Indian Red Admiral', 'Cruiser', 'White Four-ring', 
    'Sri Lankan Jewel Four-ring', 'Plum Judy', "Hampson's Hedge Blue", 'Common Hedge Blue', 'Purple Leafblue', 
    'Pointed Ciliate Blue', 'Aberrant Bushblue', 'Large Oakblue', 'Centaur Oakblue', "Sri Lankan Ormiston's Oakblue", 
    'African Babul Blue', 'Bright Babul Blue', 'Plane', 'Angled Pierrot', 'Common Pierrot', 'Common Tinsel', 
    'Silver Forget-me-not', 'Forget-me-not', 'Plain Hedge Blue', 'Common Imperial', 'Lime Blue', 'Plains Cupid', 
    'Small Cupid', 'Indian Sunbeam', 'Cornelian', 'Banded Blue Pierrot', 'Gram Blue', 'Indian Cupid', 'Grass Jewel', 
    'Brown Onyx', 'Blue Onyx', 'Nilgiri Tit', 'Pointed Lineblue', 'Silverstreak Blue', 'Metallic Cerulean', 
    'Dark Cerulean', 'Common Cerulean', 'Sri Lankan Cerulean', 'Sri Lankan Milky Cerulean', 'Pea Blue', 
    'Zebra Blue', 'Yamfly', 'Malayan', 'Rounded Six Lineblue', 'Opaque Six Lineblue', 'Dark Ceylon Six Lineblue', 
    'Pale Four Lineblue', 'Transparent Six Lineblue', "Sri Lankan Woodhouse's Four Lineblue", 'Large Four Lineblue', 
    'Sri Lankan Pale Ceylon Six Lineblue', 'Quaker', 'Dingy Lineblue', 'White Royal', 'Tailless Lineblue', 
    'Common Lineblue', 'White-tipped Lineblue', 'Indian Red Flash', 'Malabar Flash', 'Slate Flash', 'Indigo Flash', 
    'Monkey-puzzle', 'Apefly', 'Scarce Shot Silverline', 'Green’s Silverline', 'Ceylon Silverline', 
    'Long -banded Silverline', 'Sri Lankan Clouded Silverline', 'Plumbeous Silverline', 'Common Silverline', 
    'Common Acacia Blue', 'Sri Lankan Indigo Royal', 'Peacock Royal', 'Plains Blue Royal', 'Red Pierrot', 
    "Butler's Spotted Pierrot", 'Striped Pierrot', 'White Hedge Blue', 'Sri Lankan Hedge Blue', 'Singalese Hedge Blue', 
    'Common Guava Blue', 'Large Guava Blue', 'Redspot', 'Dark Grass Blue', 'Lesser Grass Blue', 'Tiny Grass Blue', 
    'Bush Hopper', 'Brown Awl', 'Sri Lankan Paintbrush Swift', 'Sri Lankan Hedge Hopper', 'Orange-tailed Awl', 
    "Wallace's Swift", 'Banded Orange Awlet', 'Blank Swift', 'Philippine Swift', 'Ceylon Golden Angle', 'Golden Angle', 
    'Sri Lankan Black Flat', 'Yellow Palm Dart', 'Indian Awl King', 'Tricolour Pied Flat', 'Banded Redeye', 
    'Giant Redeye', 'African Marbled Skipper', 'Rare Ace', 'Ceylon Ace', 'Ceylon Awl / Common Awl', 'Common Banded Awl', 
    'White-banded Awl', 'Tree Flitter', 'Chestnut Bob', 'Common Redeye', 'Restricted Demon', 'Common Banded Demon', 
    'Common Dartlet', 'Smallest Swift', 'Little Branded Swift', 'Conjoined Swift', 'Small Branded Swift', 
    'Large Branded Swift', 'Indian Dart/Pallid Dart', 'Common Dart', 'Tropic Dart', 'Common Small Flat', 
    'Indian Skipper', 'Indian Palm Bob', 'Ceylon Palm Bob', 'Ceylon Snow Flat', 'Water Snow Flat', 'Black Angle', 
    'Common Grass Dart', 'Dark Palmdart', 'Pale Palmdart', 'Sri Lankan Decorated Ace', 'Grass Demon'
];